# Generated by Django 5.2.8 on 2025-12-13 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_passwordresetotp'),
    ]

    operations = [
        migrations.AddField(
            model_name='passwordresetotp',
            name='otp_type',
            field=models.CharField(choices=[('send', 'Send'), ('resend', 'Resend')], default='send', max_length=10),
        ),
    ]
