# Generated by Django 5.2.8 on 2026-01-22 16:58

import django.contrib.auth.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_passwordresetotp_otp_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminManagement',
            fields=[
            ],
            options={
                'verbose_name': 'Admin Management',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('accounts.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
