# Generated by Django 5.2.8 on 2026-01-24 14:05

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('date', models.DateField()),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('location', models.CharField(blank=True, max_length=255, null=True)),
                ('format', models.CharField(choices=[('On-site', 'On-site'), ('Online', 'Online'), ('Hybrid', 'Hybrid')], default='On-site', max_length=20)),
                ('image', models.ImageField(blank=True, null=True, upload_to='events/')),
                ('speakers', models.JSONField(blank=True, help_text='Example: [{"name": "Aryush Khatri", "profession": "Backend Engineer"}]', null=True)),
                ('what_to_expect', models.JSONField(blank=True, help_text='Example: ["Hands-on workshop", "Networking session", "Live demo"]', null=True)),
                ('community', models.ForeignKey(limit_choices_to={'role': 'community'}, on_delete=django.db.models.deletion.CASCADE, related_name='events', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_events', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['date', 'start_time'],
            },
        ),
    ]
