# Generated by Django 5.2.8 on 2026-03-28 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_eventregistration'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='max_participants',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='registration_deadline',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='eventregistration',
            name='attendance',
            field=models.CharField(choices=[('NA', 'Not Marked'), ('P', 'Present'), ('A', 'Absent')], default='NA', max_length=2),
        ),
    ]
