"""
Jazzmin configuration for HCKonnect admin.

Imported into settings.py as JAZZMIN_SETTINGS and JAZZMIN_UI_TWEAKS.
Brand colors match FRONTEND/src/index.css:
  primary #75BF44, accent/secondary #FAFAFA, dark surfaces #09090b / #3c3c3c
"""

JAZZMIN_SETTINGS = {
    "site_title": "HCKonnect Admin",
    "site_header": "HCKonnect",
    "site_brand": "HCKonnect",
    "site_logo": "admin/hckonnect/logo.png",
    "login_logo": "admin/hckonnect/logo-login.png",
    "login_logo_dark": "admin/hckonnect/logo-login.png",
    "site_logo_classes": "img-circle",
    "site_icon": "admin/hckonnect/favicon.png",
    "welcome_sign": "Welcome to the HCKonnect control panel",
    "copyright": "Herald College — HCKonnect",
    "search_model": ["accounts.User", "accounts.CommunityUser"],
    "user_avatar": None,
    "topmenu_links": [
        {"name": "Dashboard", "url": "admin:index", "permissions": ["auth.view_user"]},
        {"name": "API docs", "url": "/", "new_window": True},
    ],
    "usermenu_links": [
        {"model": "accounts.user"},
    ],
    "show_sidebar": True,
    "navigation_expanded": True,
    "hide_apps": [],
    "hide_models": [],
    "order_with_respect_to": [
        "accounts",
        "communities",
        "contents",
        "discussion",
        "events",
        "notifications",
    ],
    "custom_links": {},
    "icons": {
        "auth": "fas fa-shield-alt",
        "auth.group": "fas fa-users-cog",
        "accounts": "fas fa-id-card",
        "accounts.user": "fas fa-user",
        "accounts.communityuser": "fas fa-university",
        "accounts.adminmanagement": "fas fa-user-shield",
        "accounts.passwordresetotp": "fas fa-key",
        "accounts.contactusmessage": "fas fa-envelope",
        "communities": "fas fa-users",
        "communities.communitymembership": "fas fa-user-friends",
        "communities.communityvacancy": "fas fa-briefcase",
        "communities.vacancyapplication": "fas fa-file-signature",
        "contents": "fas fa-newspaper",
        "contents.announcement": "fas fa-bullhorn",
        "contents.post": "fas fa-stream",
        "contents.postcomment": "fas fa-comment",
        "contents.postreaction": "fas fa-heart",
        "contents.resource": "fas fa-folder-open",
        "discussion": "fas fa-comments",
        "discussion.discussionpanel": "fas fa-comment-dots",
        "discussion.discussionreply": "fas fa-reply",
        "discussion.reaction": "fas fa-smile",
        "events": "fas fa-calendar-alt",
        "events.event": "fas fa-calendar-check",
        "events.eventregistration": "fas fa-ticket-alt",
        "notifications": "fas fa-bell",
        "notifications.notification": "fas fa-bell",
    },
    "default_icon_parents": "fas fa-chevron-circle-right",
    "default_icon_children": "fas fa-circle",
    "related_modal_active": True,
    "custom_css": "admin/hckonnect/jazzmin-custom.css",
    "custom_js": None,
    "use_google_fonts_cdn": True,
    "show_ui_builder": False,
    "changeform_format": "horizontal_tabs",
    "changeform_format_overrides": {
        "accounts.user": "collapsible",
        "discussion.discussionpanel": "vertical_tabs",
    },
}

JAZZMIN_UI_TWEAKS = {
    "navbar_small_text": False,
    "footer_small_text": False,
    "body_small_text": False,
    "brand_small_text": False,
    "brand_colour": "navbar-dark",
    "accent": "accent-primary",
    "navbar": "navbar-dark navbar-dark",
    "no_navbar_border": False,
    "navbar_fixed": True,
    "layout_boxed": False,
    "footer_fixed": False,
    "sidebar_fixed": True,
    "sidebar": "sidebar-dark-primary",
    "sidebar_nav_small_text": False,
    "sidebar_disable_expand_user": False,
    "sidebar_nav_child_indent": True,
    "sidebar_nav_compact_style": False,
    "sidebar_nav_legacy_style": False,
    "sidebar_nav_flat_style": False,
    "theme": "default",
    "dark_mode_theme": None,
    "button_classes": {
        "primary": "btn-primary",
        "secondary": "btn-secondary",
        "info": "btn-info",
        "warning": "btn-warning",
        "danger": "btn-danger",
        "success": "btn-success",
    },
}
