# Generated by Django 5.2.8 on 2026-03-27 04:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='type',
            field=models.CharField(choices=[('membership', 'Membership'), ('role_change', 'Role Change'), ('vacancy', 'Vacancy/Recruitment'), ('event', 'Event'), ('announcement', 'Announcement'), ('discussion', 'Discussion'), ('post', 'Post'), ('resource', 'Resource'), ('message', 'Message')], max_length=20),
        ),
    ]
