# Generated by Django 5.2.8 on 2026-05-26 02:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0002_alter_notification_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='type',
            field=models.CharField(choices=[('membership', 'Membership'), ('role_change', 'Role Change'), ('vacancy', 'Vacancy/Recruitment'), ('event', 'Event'), ('announcement', 'Announcement'), ('discussion', 'Discussion'), ('post', 'Post'), ('resource', 'Resource'), ('message', 'Message'), ('mention', 'Mention')], max_length=20),
        ),
    ]
