# Generated by Django 5.2.8 on 2026-05-26 02:58

import contents.resource_storage
import contents.resource_utils
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contents', '0004_resource_file_metadata'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='postcomment',
            name='mentioned_users',
            field=models.ManyToManyField(blank=True, related_name='mentioned_in_comments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='resource',
            name='file',
            field=models.FileField(blank=True, null=True, storage=contents.resource_storage.ResourceCloudinaryStorage(), upload_to=contents.resource_utils.resource_upload_path),
        ),
    ]
