# Generated by Django 5.2.8 on 2026-02-19 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discussion', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='discussionpanel',
            name='tags',
        ),
        migrations.AlterModelOptions(
            name='discussionpanel',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterField(
            model_name='reaction',
            name='reaction_type',
            field=models.CharField(default='like', max_length=10),
        ),
        migrations.DeleteModel(
            name='Tag',
        ),
    ]
