# Generated by Django 5.2.8 on 2026-05-26 08:27

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discussion', '0002_remove_discussionpanel_tags_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='discussionreply',
            name='mentioned_users',
            field=models.ManyToManyField(blank=True, related_name='mentioned_in_replies', to=settings.AUTH_USER_MODEL),
        ),
    ]
