# Generated by Django 5.2.8 on 2026-05-26 17:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('discussion', '0004_discussionreply_topic_parent_idx'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='discussionreply',
            name='discussion_reply_topic_parent_idx',
        ),
    ]
