# Generated by Django 5.2.8 on 2025-12-22 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communities', '0002_alter_communitymembership_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='communitymembership',
            name='role',
            field=models.CharField(choices=[('member', 'Member'), ('moderator', 'Moderator'), ('leader', 'Leader')], default='member', max_length=20),
        ),
    ]
