# Generated by Django 5.2.8 on 2026-01-24 13:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('communities', '0006_announcement_visibility_event'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Event',
        ),
    ]
