# Generated by Django 5.2.8 on 2026-01-28 15:05

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communities', '0007_delete_event'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='communitymembership',
            name='status',
        ),
        migrations.AddField(
            model_name='communityvacancy',
            name='deadline',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='announcement',
            name='visibility',
            field=models.CharField(choices=[('public', 'Public'), ('all_community', 'All Community Only'), ('private', 'Private')], default='public', max_length=20),
        ),
        migrations.AlterField(
            model_name='communitymembership',
            name='role',
            field=models.CharField(choices=[('member', 'Member'), ('representative', 'Community Representative')], default='member', max_length=20),
        ),
        migrations.CreateModel(
            name='VacancyApplication',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('resume', models.FileField(blank=True, null=True, upload_to='applications/')),
                ('message', models.TextField(blank=True)),
                ('applied_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(limit_choices_to={'role': 'student'}, on_delete=django.db.models.deletion.CASCADE, related_name='vacancy_applications', to=settings.AUTH_USER_MODEL)),
                ('vacancy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='communities.communityvacancy')),
            ],
            options={
                'unique_together': {('user', 'vacancy')},
            },
        ),
    ]
