# Generated by Django 5.2.8 on 2026-01-29 12:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communities', '0008_remove_communitymembership_status_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='communitymembership',
            options={'verbose_name': 'Community Membership'},
        ),
        migrations.AlterUniqueTogether(
            name='communitymembership',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='communitymembership',
            name='user',
            field=models.OneToOneField(limit_choices_to={'role': 'student'}, on_delete=django.db.models.deletion.CASCADE, related_name='membership', to=settings.AUTH_USER_MODEL),
        ),
    ]
