# Generated by Django 5.2.8 on 2026-02-04 14:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('communities', '0009_alter_communitymembership_options_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Announcement',
        ),
    ]
